services:
  app:
    build: .
    ports:
      - "8011:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: imt_cursos
      DB_USER: root
      DB_PASSWORD: secret
      BASE_URL: /
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: imt_cursos
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: